-- Initial supported regions for TourAPI-backed travel recommendations.
-- Flyway runs before Hibernate, so create the table for a fresh database.

CREATE TABLE IF NOT EXISTS regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(80) NOT NULL,
    region_type VARCHAR(20) NOT NULL,
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    description TEXT,
    image_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_regions_parent FOREIGN KEY (parent_id) REFERENCES regions(id),
    CONSTRAINT uk_region_parent_name UNIQUE (parent_id, name),
    CONSTRAINT regions_region_type_check
        CHECK (region_type IN ('PROVINCE', 'CITY', 'COUNTY', 'DISTRICT', 'TOWN'))
);

MERGE INTO regions r
USING (
    VALUES
        ('전주', CAST(35.8242000 AS NUMERIC(10, 7)), CAST(127.1480000 AS NUMERIC(10, 7))),
        ('군산', CAST(35.9677000 AS NUMERIC(10, 7)), CAST(126.7368000 AS NUMERIC(10, 7))),
        ('남원', CAST(35.4164000 AS NUMERIC(10, 7)), CAST(127.3904000 AS NUMERIC(10, 7))),
        ('목포', CAST(34.8118000 AS NUMERIC(10, 7)), CAST(126.3922000 AS NUMERIC(10, 7))),
        ('광주', CAST(35.1595000 AS NUMERIC(10, 7)), CAST(126.8526000 AS NUMERIC(10, 7))),
        ('순천', CAST(34.9506000 AS NUMERIC(10, 7)), CAST(127.4872000 AS NUMERIC(10, 7))),
        ('여수', CAST(34.7604000 AS NUMERIC(10, 7)), CAST(127.6622000 AS NUMERIC(10, 7))),
        ('보성', CAST(34.7715000 AS NUMERIC(10, 7)), CAST(127.0801000 AS NUMERIC(10, 7))),
        ('완도', CAST(34.3110000 AS NUMERIC(10, 7)), CAST(126.7551000 AS NUMERIC(10, 7)))
) AS s(name, latitude, longitude)
ON r.parent_id IS NULL AND r.name = s.name
WHEN MATCHED THEN
    UPDATE SET latitude = s.latitude,
               longitude = s.longitude,
               region_type = 'CITY',
               is_active = TRUE
WHEN NOT MATCHED THEN
    INSERT (parent_id, name, region_type, latitude, longitude, is_active)
    VALUES (NULL, s.name, 'CITY', s.latitude, s.longitude, TRUE);
